# -*- coding: utf-8 -*-
"""PAN_card_Detection (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qClC1gTT7_EFdvztDbl4_bIEipOOGw1
"""

from skimage.metrics import structural_similarity
import imutils
import cv2
from PIL import Image
import requests

!mkdir pan_card_tampering
!mkdir pan_card_tampering/image

#to update image and display
original=Image.open(requests.get('https://www.thestatesman.com/wp-content/uploads/2019/07/pan-card.jpg', stream=True).raw)
tampered=Image.open(requests.get('https://assets1.cleartax-cdn.com/s/img/20170526124335/Pan4.png', stream=True).raw)

#file format of the source file
print("original image format :"),original.format
print("tampered image format :"),tampered.format

#image size given in pixels size is given as 2 tuples(width,height)
print("original image size: "),original.size
print("tampered image size: "),tampered.size

original=original.resize((250,160))
print(original.size)
original.save('pan_card_tampering/image/original.png')#Save image
tampered = tampered.resize((250,160))
print(tampered.size)
tampered.save('pan_card_tampering/image/tampered.png')#Saves image

# Change image type if required from png to jpg
tampered = Image.open('pan_card_tampering/image/tampered.png')
tampered.save('pan_card_tampering/image/tampered.png')#can do png to jpg

original

tampered

#to load the 2 images
original=cv2.imread('pan_card_tampering/image/original.png')
tampered=cv2.imread('pan_card_tampering/image/tampered.png')

# convert image to gray scale for better understanding by the opencv library
original_gray=cv2.cvtColor(original,cv2.COLOR_BGR2GRAY)
tampered_gray=cv2.cvtColor(tampered,cv2.COLOR_BGR2GRAY)

#structural similarity between the two images are considered
(score,diff)=structural_similarity(original_gray,tampered_gray,full=True)
diff=(diff*255).astype("uint8")
print("SSIM :{}".format(score))

thresh=cv2.threshold(diff,0,255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
cnts=cv2.findContours(thresh.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnts=imutils.grab_contours(cnts)

for c in cnts:
    # applying contours on image
    (x, y, w, h) = cv2.boundingRect(c)
    cv2.rectangle(original, (x, y), (x + w, y + h), (0, 0, 255), 2)
    cv2.rectangle(tampered, (x, y), (x + w, y + h), (0, 0, 255), 2)

#original image with contour
print("the original image")
Image.fromarray(original)

#tampered image with contour
print("the tampered image")
Image.fromarray(tampered)

#difference image with black
print("the difference image in black is shown")
Image.fromarray(diff)

#difference image in white
print("the difference image in white is shown")
Image.fromarray(thresh)

